/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Organization */
        post: operations["create_organization_api_organizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/current/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_organizations_current_members_get"];
        put?: never;
        /** Create Member */
        post: operations["create_member_api_organizations_current_members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Classes */
        get: operations["list_classes_api_classes_get"];
        put?: never;
        /** Create Class */
        post: operations["create_class_api_classes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classes/{class_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Class */
        get: operations["get_class_api_classes__class_id__get"];
        put?: never;
        post?: never;
        /** Delete Class */
        delete: operations["delete_class_api_classes__class_id__delete"];
        options?: never;
        head?: never;
        /** Update Class */
        patch: operations["update_class_api_classes__class_id__patch"];
        trace?: never;
    };
    "/api/classes/{class_id}/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Student */
        post: operations["create_student_api_classes__class_id__students_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Materials */
        get: operations["list_materials_api_materials_get"];
        put?: never;
        /** Upload Material */
        post: operations["upload_material_api_materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Material */
        get: operations["get_material_api_materials__material_id__get"];
        put?: never;
        post?: never;
        /** Delete Material */
        delete: operations["delete_material_api_materials__material_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Generation */
        post: operations["create_generation_api_generation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generation/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Generation */
        get: operations["get_generation_api_generation__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generation/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Generation */
        post: operations["retry_generation_api_generation__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Packages */
        get: operations["list_packages_api_packages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Package */
        get: operations["get_package_api_packages__package_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}/blocks/{block_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Block */
        delete: operations["delete_block_api_packages__package_id__blocks__block_id__delete"];
        options?: never;
        head?: never;
        /** Update Block */
        patch: operations["update_block_api_packages__package_id__blocks__block_id__patch"];
        trace?: never;
    };
    "/api/packages/{package_id}/blocks/{block_id}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle Block Lock */
        post: operations["toggle_block_lock_api_packages__package_id__blocks__block_id__lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}/blocks/{block_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate Block */
        post: operations["regenerate_block_api_packages__package_id__blocks__block_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}/blocks/{block_id}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Copy Block */
        post: operations["copy_block_api_packages__package_id__blocks__block_id__copy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}/blocks/{block_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move Block */
        post: operations["move_block_api_packages__package_id__blocks__block_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_api_packages__package_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}/versions/{version_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Version */
        post: operations["restore_version_api_packages__package_id__versions__version_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Package */
        post: operations["approve_package_api_packages__package_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}/submit-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Package Review */
        post: operations["submit_package_review_api_packages__package_id__submit_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}/preview/{variant}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Package */
        get: operations["preview_package_api_packages__package_id__preview__variant__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}/export/{variant}.{file_format}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Export */
        get: operations["download_export_api_packages__package_id__export__variant___file_format__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/ai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ai Settings */
        get: operations["ai_settings_api_settings_ai_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BlockMove */
        BlockMove: {
            /**
             * Direction
             * @enum {string}
             */
            direction: "up" | "down";
        };
        /** BlockUpdate */
        BlockUpdate: {
            /** Title */
            title?: string | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /** Instructions */
            instructions?: string | null;
            /** Teacher Notes */
            teacher_notes?: string | null;
            /** Student Content */
            student_content?: string | null;
            /** Questions */
            questions?: components["schemas"]["Question"][] | null;
        };
        /** Body_upload_material_api_materials_post */
        Body_upload_material_api_materials_post: {
            /** File */
            file: string;
            /**
             * Grade
             * @default
             */
            grade: string;
            /**
             * Chapter
             * @default
             */
            chapter: string;
            /**
             * Topic
             * @default
             */
            topic: string;
            /**
             * Difficulty
             * @default 中等
             */
            difficulty: string;
            /**
             * Tags
             * @default
             */
            tags: string;
        };
        /** ClassCreate */
        ClassCreate: {
            /** Name */
            name: string;
            /** Grade */
            grade: string;
            /**
             * Material Name
             * @default 自訂教材
             */
            material_name: string;
            /**
             * Weekly Schedule
             * @default
             */
            weekly_schedule: string;
            /** Objectives */
            objectives?: string[];
            /**
             * Overall Level
             * @default 中等
             */
            overall_level: string;
            /**
             * Learned Content
             * @default
             */
            learned_content: string;
            /** Common Errors */
            common_errors?: string[];
            /**
             * Teaching Preferences
             * @default
             */
            teaching_preferences: string;
            /**
             * Homework Days
             * @default 4
             */
            homework_days: number;
            /**
             * Homework Minutes
             * @default 30
             */
            homework_minutes: number;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Students */
            students?: components["schemas"]["StudentCreate"][];
        };
        /** ClassUpdate */
        ClassUpdate: {
            /** Name */
            name?: string | null;
            /** Grade */
            grade?: string | null;
            /** Material Name */
            material_name?: string | null;
            /** Weekly Schedule */
            weekly_schedule?: string | null;
            /** Objectives */
            objectives?: string[] | null;
            /** Overall Level */
            overall_level?: string | null;
            /** Learned Content */
            learned_content?: string | null;
            /** Common Errors */
            common_errors?: string[] | null;
            /** Teaching Preferences */
            teaching_preferences?: string | null;
            /** Homework Days */
            homework_days?: number | null;
            /** Homework Minutes */
            homework_minutes?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** ClassView */
        ClassView: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Grade */
            grade: string;
            /** Material Name */
            material_name: string;
            /** Weekly Schedule */
            weekly_schedule: string;
            /** Objectives */
            objectives: string[];
            /** Overall Level */
            overall_level: string;
            /** Learned Content */
            learned_content: string;
            /** Common Errors */
            common_errors: string[];
            /** Teaching Preferences */
            teaching_preferences: string;
            /** Homework Days */
            homework_days: number;
            /** Homework Minutes */
            homework_minutes: number;
            /** Notes */
            notes: string;
            /** Students */
            students?: components["schemas"]["StudentView"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CurrentUser */
        CurrentUser: {
            /** Id */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name: string;
            /** Organization Id */
            organization_id: string;
            /** Organization Name */
            organization_name: string;
            role: components["schemas"]["Role"];
        };
        /** GenerationRequest */
        GenerationRequest: {
            /** Class Id */
            class_id: string;
            /** Material Ids */
            material_ids: string[];
            /**
             * Lesson Date
             * Format: date
             */
            lesson_date: string;
            /**
             * Lesson Minutes
             * @default 120
             */
            lesson_minutes: number;
            /** Objectives */
            objectives: string[];
            /** Difficulty Ratio */
            difficulty_ratio?: {
                [key: string]: number;
            };
            /** Question Types */
            question_types?: {
                [key: string]: number;
            };
            /**
             * Homework Days
             * @default 4
             */
            homework_days: number;
            /**
             * Include Weekly Quiz
             * @default true
             */
            include_weekly_quiz: boolean;
            /**
             * Include Parent Report
             * @default true
             */
            include_parent_report: boolean;
            /**
             * Teacher Instructions
             * @default
             */
            teacher_instructions: string;
            /** Modules */
            modules?: string[];
        };
        /** GenerationRunView */
        GenerationRunView: {
            /** Id */
            id: string;
            /** Lesson Package Id */
            lesson_package_id: string | null;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Progress Message */
            progress_message: string;
            /** Attempt Count */
            attempt_count: number;
            /** Failure Reason */
            failure_reason: string | null;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Token Usage */
            token_usage: {
                [key: string]: number;
            } | null;
            /** Validation Summary */
            validation_summary: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HomeworkDay */
        HomeworkDay: {
            /** Day */
            day: number;
            /** Title */
            title: string;
            /** Estimated Minutes */
            estimated_minutes: number;
            /** Vocabulary */
            vocabulary?: string[];
            /** Questions */
            questions?: components["schemas"]["Question"][];
            /** Review Note */
            review_note: string;
        };
        /** LessonBlock */
        LessonBlock: {
            /** Id */
            id?: string | null;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Duration Minutes */
            duration_minutes: number;
            /**
             * Instructions
             * @default
             */
            instructions: string;
            /**
             * Teacher Notes
             * @default
             */
            teacher_notes: string;
            /**
             * Student Content
             * @default
             */
            student_content: string;
            /** Questions */
            questions?: components["schemas"]["Question"][];
            /** Source References */
            source_references?: components["schemas"]["SourceReference"][];
            /**
             * Locked
             * @default false
             */
            locked: boolean;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Organization Id */
            organization_id?: string | null;
        };
        /** MaterialChunkView */
        MaterialChunkView: {
            /** Id */
            id: string;
            /** Sequence */
            sequence: number;
            /** Text */
            text: string;
            /** Page Number */
            page_number: number | null;
            /** Paragraph Number */
            paragraph_number: number | null;
        };
        /** MaterialView */
        MaterialView: {
            /**
             * Grade
             * @default
             */
            grade: string;
            /**
             * Chapter
             * @default
             */
            chapter: string;
            /**
             * Topic
             * @default
             */
            topic: string;
            /**
             * Difficulty
             * @default 中等
             */
            difficulty: string;
            /** Tags */
            tags?: string[];
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Media Type */
            media_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Parse Status */
            parse_status: string;
            /** Extracted Text */
            extracted_text: string;
            /** Parse Error */
            parse_error: string | null;
            /** Chunks */
            chunks?: components["schemas"]["MaterialChunkView"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MemberCreate */
        MemberCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name: string;
            /** Password */
            password: string;
            /** @default teacher */
            role: components["schemas"]["Role"];
        };
        /** MemberView */
        MemberView: {
            /** Id */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["Role"];
        };
        /** OrganizationCreate */
        OrganizationCreate: {
            /** Name */
            name: string;
        };
        /** PackageView */
        PackageView: {
            /** Id */
            id: string;
            /** Class Id */
            class_id: string;
            /** Title */
            title: string;
            /**
             * Lesson Date
             * Format: date
             */
            lesson_date: string;
            /** Status */
            status: string;
            /** Current Version */
            current_version: number;
            /** Total Minutes */
            total_minutes: number;
            /** Objectives */
            objectives: string[];
            /** Blocks */
            blocks: components["schemas"]["LessonBlock"][];
            /** Homework Days */
            homework_days: components["schemas"]["HomeworkDay"][];
            weekly_quiz: components["schemas"]["WeeklyQuiz"] | null;
            parent_report: components["schemas"]["ParentReport"] | null;
            /** Validation Issues */
            validation_issues: components["schemas"]["ValidationIssue"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ParentReport */
        ParentReport: {
            /** Homework Completion */
            homework_completion: string;
            /** Quiz Performance */
            quiz_performance: string;
            /** Progress */
            progress: string;
            /** Main Weaknesses */
            main_weaknesses: string[];
            /** Next Week Focus */
            next_week_focus: string[];
            /** Teacher Notes */
            teacher_notes: string;
        };
        /** Question */
        Question: {
            /** Id */
            id?: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "vocabulary" | "multiple_choice" | "cloze" | "reading" | "translation" | "writing" | "analysis";
            /** Prompt */
            prompt: string;
            /** Options */
            options?: string[];
            /**
             * Answer
             * @default
             */
            answer: string;
            /**
             * Explanation
             * @default
             */
            explanation: string;
            /**
             * Points
             * @default 1
             */
            points: number;
            /**
             * Multiple Answers
             * @default false
             */
            multiple_answers: boolean;
            /** Reading Reference */
            reading_reference?: string | null;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "owner" | "admin" | "teacher";
        /** SourceReference */
        SourceReference: {
            /** Source Material Id */
            source_material_id: string;
            /** Material Name */
            material_name: string;
            /** Chunk Id */
            chunk_id: string;
            /** Excerpt */
            excerpt: string;
            /** Page Number */
            page_number?: number | null;
            /** Paragraph Number */
            paragraph_number?: number | null;
        };
        /** StudentCreate */
        StudentCreate: {
            /** Alias */
            alias: string;
            /** Weaknesses */
            weaknesses?: string[];
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** StudentView */
        StudentView: {
            /** Alias */
            alias: string;
            /** Weaknesses */
            weaknesses?: string[];
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Id */
            id: string;
            /** Class Id */
            class_id: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            user: components["schemas"]["CurrentUser"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /** Code */
            code: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "fatal";
            /** Message */
            message: string;
            /** Block Id */
            block_id?: string | null;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** VersionView */
        VersionView: {
            /** Id */
            id: string;
            /** Version Number */
            version_number: number;
            /** Change Summary */
            change_summary: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** WeeklyQuiz */
        WeeklyQuiz: {
            /** Title */
            title: string;
            /** Suggested Minutes */
            suggested_minutes: number;
            /** Total Points */
            total_points: number;
            /** Questions */
            questions: components["schemas"]["Question"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
        };
    };
    create_organization_api_organizations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_organizations_current_members_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberView"][];
                };
            };
        };
    };
    create_member_api_organizations_current_members_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_classes_api_classes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassView"][];
                };
            };
        };
    };
    create_class_api_classes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_class_api_classes__class_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_class_api_classes__class_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_class_api_classes__class_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_student_api_classes__class_id__students_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_materials_api_materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialView"][];
                };
            };
        };
    };
    upload_material_api_materials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_material_api_materials_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_api_materials__material_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_material_api_materials__material_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_generation_api_generation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_generation_api_generation__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_generation_api_generation__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_packages_api_packages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageView"][];
                };
            };
        };
    };
    get_package_api_packages__package_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_block_api_packages__package_id__blocks__block_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_block_api_packages__package_id__blocks__block_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_block_lock_api_packages__package_id__blocks__block_id__lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_block_api_packages__package_id__blocks__block_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copy_block_api_packages__package_id__blocks__block_id__copy_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_block_api_packages__package_id__blocks__block_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockMove"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_packages__package_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_version_api_packages__package_id__versions__version_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_package_api_packages__package_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_package_review_api_packages__package_id__submit_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_package_api_packages__package_id__preview__variant__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
                variant: "student" | "teacher" | "homework" | "quiz" | "parent";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_export_api_packages__package_id__export__variant___file_format__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
                variant: "student" | "teacher" | "homework" | "quiz" | "parent";
                file_format: "pdf" | "docx";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_settings_api_settings_ai_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
