"""initial schema

Revision ID: 98de56af41b1
Revises:
Create Date: 2026-08-08 14:52:09.121143
"""

from collections.abc import Sequence

import sqlalchemy as sa

import lessonforge.models
from alembic import op

revision: str = "98de56af41b1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_logs_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_logs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_organization_id"), "audit_logs", ["organization_id"], unique=False
    )
    op.create_table(
        "classes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("grade", sa.String(length=20), nullable=False),
        sa.Column("material_name", sa.String(length=120), nullable=False),
        sa.Column("weekly_schedule", sa.String(length=120), nullable=False),
        sa.Column("objectives", sa.JSON(), nullable=False),
        sa.Column("overall_level", sa.String(length=30), nullable=False),
        sa.Column("learned_content", sa.Text(), nullable=False),
        sa.Column("common_errors", sa.JSON(), nullable=False),
        sa.Column("teaching_preferences", sa.Text(), nullable=False),
        sa.Column("homework_days", sa.Integer(), nullable=False),
        sa.Column("homework_minutes", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_classes_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classes")),
    )
    op.create_index(
        op.f("ix_classes_organization_id"), "classes", ["organization_id"], unique=False
    )
    op.create_table(
        "lesson_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("structure", sa.JSON(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_lesson_templates_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lesson_templates")),
    )
    op.create_index(
        op.f("ix_lesson_templates_organization_id"),
        "lesson_templates",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "memberships",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint(
            "organization_id", "user_id", name=op.f("uq_memberships_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_memberships_organization_id"), "memberships", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "source_materials",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("uploaded_by_id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("grade", sa.String(length=20), nullable=False),
        sa.Column("chapter", sa.String(length=120), nullable=False),
        sa.Column("topic", sa.String(length=120), nullable=False),
        sa.Column("difficulty", sa.String(length=30), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("parse_status", sa.String(length=20), nullable=False),
        sa.Column("extracted_text", sa.Text(), nullable=False),
        sa.Column("parse_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_source_materials_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"], ["users.id"], name=op.f("fk_source_materials_uploaded_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_materials")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_source_materials_storage_key")),
    )
    op.create_index(
        op.f("ix_source_materials_organization_id"),
        "source_materials",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_materials_parse_status"), "source_materials", ["parse_status"], unique=False
    )
    op.create_table(
        "lesson_packages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("class_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("lesson_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("total_minutes", sa.Integer(), nullable=False),
        sa.Column("objectives", sa.JSON(), nullable=False),
        sa.Column("homework_days", sa.JSON(), nullable=False),
        sa.Column("weekly_quiz", sa.JSON(), nullable=True),
        sa.Column("parent_report", sa.JSON(), nullable=True),
        sa.Column("generation_settings", sa.JSON(), nullable=False),
        sa.Column("approved_by_id", sa.String(length=36), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by_id"], ["users.id"], name=op.f("fk_lesson_packages_approved_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
            name=op.f("fk_lesson_packages_class_id_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_lesson_packages_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lesson_packages")),
    )
    op.create_index(
        op.f("ix_lesson_packages_class_id"), "lesson_packages", ["class_id"], unique=False
    )
    op.create_index(
        op.f("ix_lesson_packages_organization_id"),
        "lesson_packages",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_lesson_packages_status"), "lesson_packages", ["status"], unique=False)
    op.create_table(
        "material_chunks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("source_material_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("paragraph_number", sa.Integer(), nullable=True),
        sa.Column("chapter", sa.String(length=120), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("embedding", lessonforge.models.VectorOrJSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_material_chunks_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_material_id"],
            ["source_materials.id"],
            name=op.f("fk_material_chunks_source_material_id_source_materials"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_chunks")),
    )
    op.create_index(
        op.f("ix_material_chunks_organization_id"),
        "material_chunks",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_material_chunks_source_material_id"),
        "material_chunks",
        ["source_material_id"],
        unique=False,
    )
    op.create_table(
        "student_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("class_id", sa.String(length=36), nullable=False),
        sa.Column("alias", sa.String(length=50), nullable=False),
        sa.Column("weaknesses", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
            name=op.f("fk_student_profiles_class_id_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_student_profiles_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_profiles")),
    )
    op.create_index(
        op.f("ix_student_profiles_class_id"), "student_profiles", ["class_id"], unique=False
    )
    op.create_index(
        op.f("ix_student_profiles_organization_id"),
        "student_profiles",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "generation_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("lesson_package_id", sa.String(length=36), nullable=True),
        sa.Column("class_id", sa.String(length=36), nullable=False),
        sa.Column("requested_by_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("input_settings", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("progress_message", sa.String(length=160), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("token_usage", sa.JSON(), nullable=True),
        sa.Column("validation_summary", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
            name=op.f("fk_generation_runs_class_id_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lesson_package_id"],
            ["lesson_packages.id"],
            name=op.f("fk_generation_runs_lesson_package_id_lesson_packages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_generation_runs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"], ["users.id"], name=op.f("fk_generation_runs_requested_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_runs")),
    )
    op.create_index(
        op.f("ix_generation_runs_class_id"), "generation_runs", ["class_id"], unique=False
    )
    op.create_index(
        op.f("ix_generation_runs_organization_id"),
        "generation_runs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_generation_runs_status"), "generation_runs", ["status"], unique=False)
    op.create_table(
        "lesson_blocks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("lesson_package_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("block_type", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("teacher_notes", sa.Text(), nullable=False),
        sa.Column("student_content", sa.Text(), nullable=False),
        sa.Column("source_references", sa.JSON(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_package_id"],
            ["lesson_packages.id"],
            name=op.f("fk_lesson_blocks_lesson_package_id_lesson_packages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_lesson_blocks_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lesson_blocks")),
    )
    op.create_index(
        op.f("ix_lesson_blocks_lesson_package_id"),
        "lesson_blocks",
        ["lesson_package_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lesson_blocks_organization_id"), "lesson_blocks", ["organization_id"], unique=False
    )
    op.create_table(
        "lesson_package_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("lesson_package_id", sa.String(length=36), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("change_summary", sa.String(length=255), nullable=False),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_lesson_package_versions_created_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["lesson_package_id"],
            ["lesson_packages.id"],
            name=op.f("fk_lesson_package_versions_lesson_package_id_lesson_packages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_lesson_package_versions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lesson_package_versions")),
        sa.UniqueConstraint(
            "lesson_package_id",
            "version_number",
            name=op.f("uq_lesson_package_versions_lesson_package_id"),
        ),
    )
    op.create_index(
        op.f("ix_lesson_package_versions_lesson_package_id"),
        "lesson_package_versions",
        ["lesson_package_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lesson_package_versions_organization_id"),
        "lesson_package_versions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "validation_issues",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("lesson_package_id", sa.String(length=36), nullable=False),
        sa.Column("block_id", sa.String(length=36), nullable=True),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_package_id"],
            ["lesson_packages.id"],
            name=op.f("fk_validation_issues_lesson_package_id_lesson_packages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_validation_issues_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validation_issues")),
    )
    op.create_index(
        op.f("ix_validation_issues_lesson_package_id"),
        "validation_issues",
        ["lesson_package_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_validation_issues_organization_id"),
        "validation_issues",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("lesson_block_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("question_type", sa.String(length=40), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("multiple_answers", sa.Boolean(), nullable=False),
        sa.Column("reading_reference", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_block_id"],
            ["lesson_blocks.id"],
            name=op.f("fk_questions_lesson_block_id_lesson_blocks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_questions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
    )
    op.create_index(
        op.f("ix_questions_lesson_block_id"), "questions", ["lesson_block_id"], unique=False
    )
    op.create_index(
        op.f("ix_questions_organization_id"), "questions", ["organization_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_questions_organization_id"), table_name="questions")
    op.drop_index(op.f("ix_questions_lesson_block_id"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_validation_issues_organization_id"), table_name="validation_issues")
    op.drop_index(op.f("ix_validation_issues_lesson_package_id"), table_name="validation_issues")
    op.drop_table("validation_issues")
    op.drop_index(
        op.f("ix_lesson_package_versions_organization_id"), table_name="lesson_package_versions"
    )
    op.drop_index(
        op.f("ix_lesson_package_versions_lesson_package_id"), table_name="lesson_package_versions"
    )
    op.drop_table("lesson_package_versions")
    op.drop_index(op.f("ix_lesson_blocks_organization_id"), table_name="lesson_blocks")
    op.drop_index(op.f("ix_lesson_blocks_lesson_package_id"), table_name="lesson_blocks")
    op.drop_table("lesson_blocks")
    op.drop_index(op.f("ix_generation_runs_status"), table_name="generation_runs")
    op.drop_index(op.f("ix_generation_runs_organization_id"), table_name="generation_runs")
    op.drop_index(op.f("ix_generation_runs_class_id"), table_name="generation_runs")
    op.drop_table("generation_runs")
    op.drop_index(op.f("ix_student_profiles_organization_id"), table_name="student_profiles")
    op.drop_index(op.f("ix_student_profiles_class_id"), table_name="student_profiles")
    op.drop_table("student_profiles")
    op.drop_index(op.f("ix_material_chunks_source_material_id"), table_name="material_chunks")
    op.drop_index(op.f("ix_material_chunks_organization_id"), table_name="material_chunks")
    op.drop_table("material_chunks")
    op.drop_index(op.f("ix_lesson_packages_status"), table_name="lesson_packages")
    op.drop_index(op.f("ix_lesson_packages_organization_id"), table_name="lesson_packages")
    op.drop_index(op.f("ix_lesson_packages_class_id"), table_name="lesson_packages")
    op.drop_table("lesson_packages")
    op.drop_index(op.f("ix_source_materials_parse_status"), table_name="source_materials")
    op.drop_index(op.f("ix_source_materials_organization_id"), table_name="source_materials")
    op.drop_table("source_materials")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_organization_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_lesson_templates_organization_id"), table_name="lesson_templates")
    op.drop_table("lesson_templates")
    op.drop_index(op.f("ix_classes_organization_id"), table_name="classes")
    op.drop_table("classes")
    op.drop_index(op.f("ix_audit_logs_organization_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
